# Generated by Django 4.1.7 on 2023-04-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='phone',
            field=models.CharField(default='(000) 000-0000', max_length=20),
        ),
    ]
